### ISSUE TITLE
Using variables into cmd

### ISSUE THREAD

**Issue by Chamlee** [sergeysova/jq-action#1]
Hey,

Into cmd is it possible to use github input variables like : 

```yaml
- name: My cmd
  uses: sergeysova/jq-action@v2
  with:
    cmd: 'echo "version ${{ github.event.inputs.version }}"'
```
