### ISSUE TITLE
Multiline output

### ISSUE THREAD

**Issue by rosshamish** [sergeysova/jq-action#2]
Hey there, thanks for the action. Would you be open to accepting a PR that adds support for multiline output? It's helpful for example when outputting one field from each item in a list. Right now, if the `jq` output has multiple lines, only the first line is set as the output, and the rest of the lines are just written to stdout.

It would look like this:

```yml
    - name: Extract contributed themes from package.json
      uses: .sergeysova/jq-action@v2
      id: themes
      with:
        cmd: 'jq .contributes.themes[].path ${{ inputs.working-directory }}/package.json --raw-output'
        multiline: true
```

And then the multiline output can be used like

```yml
    - name: Verify each contributed theme exists
      shell: bash
      run: |
        themes_in_package_json="${{ steps.themes.outputs.value }}"
        for theme in $themes_in_package_json; do
            ....
        done
```

Let me know! Thanks.
