### ISSUE TITLE
Allow running .sh file

### ISSUE THREAD

**Issue by cakeinpanic** [sergeysova/jq-action#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hi! Can feature of providing path to the `.sh` file instead of command itself be added?

### Solution

```
  - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        with:
          cmdPath: 'scripts/cmd.sh'
```

### Alternatives

can't think about
