### ISSUE TITLE
Deprecated set-output

### ISSUE THREAD

**Issue by jorgecuesta** [sergeysova/jq-action#8]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v2

### Steps to reproduce

Create an action as explained on README.md

```yml
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        if: ${{ inputs.push == true }}
        with:
          cmd: 'jq .version apps/${{ inputs.app }}/package.json -r'
```

### Expected behavior

No warnings

### Actual behavior

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Runtime

Node v16

### Package manager

yarn v2

### OS

Linux

### Build and bundle tools

Next.js
